name: images

on:
  push:
    branches: [ main ]

jobs:
  mariadb:
    runs-on: ubuntu-latest
    steps:
      - name: Step One - Checkout Repository
        uses: actions/checkout@v3
      
      - name: Step Two - Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'

      - name: Step Three - Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Step Four - Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./mariadb/Dockerfile
          tags: classicpress/classicpress:mariadb

  nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Step One - Checkout Repository
        uses: actions/checkout@v3
      
      - name: Step Two - Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'

      - name: Step Three - Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Step Four - Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./nginx/8.0/Dockerfile
          tags: classicpress/classicpress:nginx-php8.0